# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: rails_dev_timely
  username: rails
  password: rails
  socket: /usr/local/var/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  hostname: localhost
  database: rails_prod_timely
  username: timely
  password: RqmZ2HZ.wKqm-yz6gPVH
